name: practice_cd

on:
  push:
    branches: [main]

jobs:
  image_push:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - run: npm ci
      - run: npm test
        env:
          HOST: localhost
          PORT: 6379
      
      - name: push new image to docker hub
        run: echo ${{secrets.DOCKER_PASS}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin


  deploy_work:
    needs: image_push
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
             docker start redis
             docker pull ${{secrets.DOCKER_USER}}/mynewapp:latest
             docker stop mynewapp || true
             docker rm mynewapp || true
             docker run -d --name mynewapp -p 6379:6379 -e HOST=localhost -e PORT=6379 ${{secrets.DOCKER_USER}}/mynewapp:latest

  















































        



































# name: services_tut

# on:
#   push:
#     branches: [main]

# jobs:
#   services_tut:
#     runs-on: ubuntu-latest

#     services:
#       redis:
#         image: redis:7
#         ports:
#           - 6379:6379

#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#       - run: num ci

#       - name: check redis server
#         run: node index.js
#         env:
#           HOST: localhost
#           PORT: 6379
















# name: env_tut

# on:
#   push:
#     branches: [main]

# jobs:
#   Env_tut:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - run: npm ci

#       - name: run app with env vars
#         run: node index.js
#         env:
#             APP_ENV: ci
#             PORT: 6000

# name: ci/cd

# on:
#   push:
#     branches: [main]

# jobs:
#   hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: get the code
#         uses: actions/checkout@v4

#       - name: get the node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
      
#       - name: install depts
#         run: npm ci
      
#       - name: test
#         run: npm run test






# name : practice ci/cd

# on:
#   push:
#     branches: [main]

# jobs:
#     hello:
#       runs-on: ubuntu-latest

#       steps:
#         - name: checkout the repo
#           uses: actions/checkout@v4
        
#         - name: say hello
#           run: echo "hello from actions"
        
#         - name: get file structure
#           run: ls -a

#         - name: current directory
#           run: pwd